[pytest]
minversion = 7.0
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts =
    -ra
    --strict-markers
    --strict-config
    --tb=short
markers =
    unit: tests unitarios puros (sin I/O, sin AWS)
    slow: tests que tardan más de lo normal
filterwarnings =
    error
    ignore::DeprecationWarning:botocore.*
