service: promotick-auth

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.12
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  iam:
    role: arn:aws:iam::${aws:accountId}:role/LabRole
  environment:
    USERS_TABLE_NAME: ${cf:promotick-tables-${self:provider.stage}.UsersTableName}
    AUDIT_LOGS_TABLE_NAME: ${cf:promotick-tables-${self:provider.stage}.AuditLogsTableName}
    USER_POOL_ID:
      Ref: PromotickUserPool
    USER_POOL_CLIENT_ID:
      Ref: PromotickUserPoolClient
  httpApi:
    cors: true
    authorizers:
      cognitoJwt:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl:
          Fn::Join:
            - ""
            - - "https://cognito-idp.${aws:region}.amazonaws.com/"
              - Ref: PromotickUserPool
        audience:
          - Ref: PromotickUserPoolClient

package:
  patterns:
    - "!**"
    - "src/**"
    - "!**/__pycache__/**"

functions:
  login:
    handler: src/handlers/login.handler
    description: Login con Cognito
    events:
      - httpApi:
          method: POST
          path: /auth/login

  completeNewPassword:
    handler: src/handlers/complete_new_password.handler
    description: Completa el new password del primer login
    events:
      - httpApi:
          method: POST
          path: /auth/complete-new-password

  forgotPassword:
    handler: src/handlers/forgot_password.handler
    description: Envia un código de 6 dígitos al correo
    events:
      - httpApi:
          method: POST
          path: /auth/forgot-password

  confirmForgotPassword:
    handler: src/handlers/confirm_forgot_password.handler
    description: Confirma el código y establece la nueva contraseña
    events:
      - httpApi:
          method: POST
          path: /auth/confirm-forgot-password

  createUser:
    handler: src/handlers/create_user.handler
    description: Crear usuario (solo ADMIN)
    events:
      - httpApi:
          method: POST
          path: /users
          authorizer:
            name: cognitoJwt

  listUsers:
    handler: src/handlers/list_users.handler
    description: Listar usuarios (solo ADMIN)
    events:
      - httpApi:
          method: GET
          path: /users
          authorizer:
            name: cognitoJwt

  updateUser:
    handler: src/handlers/update_user.handler
    description: Actualizar usuario (solo ADMIN)
    events:
      - httpApi:
          method: PATCH
          path: /users/{user_id}
          authorizer:
            name: cognitoJwt

resources:
  - ${file(infrastructure/cognito.yml)}
